<?php

declare(strict_types=1);

namespace App\Generated\Exceptions;

/**
 * Base exception for all API errors generated by this client.
 *
 * Catch this class to handle any HTTP-layer error from the API:
 * <code>
 * try {
 *     $client->someMethod();
 * } catch (ApiException $e) {
 *     // handle error
 * }
 * </code>
 */
class ApiException extends \RuntimeException {}